/* !!! Generated by libax_common.cmake */ 
#pragma once

#include "atlas/_ALL_atlas.h"
#include "axRectBinPacker.h"
#include "axRectBinPacker_Skyline.h"
#include "axSamplerState.h"
#include "axTexture.h"
