//==============================================================//
//                                                              //
//       This file is generated by axNodeGen                    //
//                                                              //
//==============================================================//

#include "GEO_Cube.h"

namespace Anon{ 

struct GEO_Cube::Spec : public AnonObjectSpec {
	struct Field_center : public axFieldInfo {
		Field_center(axType* type) : axFieldInfo(type, &GEO_Cube::center, "center", "Center") {
		}
		virtual void onSetToDefaultValue(axValuePtr& data) const final {
			data.value<Vec3d>() = Vec3d(0);
		};
	};
	Field_center field_center;

	struct Field_size : public axFieldInfo {
		Field_size(axType* type) : axFieldInfo(type, &GEO_Cube::size, "size", "Size") {
		}
		virtual void onSetToDefaultValue(axValuePtr& data) const final {
			data.value<Vec3d>() = Vec3d(1,1,1);
		};
	};
	Field_size field_size;

	static const Spec* s_instance;

	axArray<axFieldInfo*, 16> _fields;

	Spec(axType* type)
		: AnonObjectSpec(type)
		, field_center(type)
		, field_size(type)
	{
		s_instance = this;
		axInt ownFieldCount = 2;
		auto baseFieldCount = type->_baseClass->fields().size();
		_fields.resize(ownFieldCount + baseFieldCount);
		_fields.slice(0, baseFieldCount).copyValues(type->_baseClass->fields());
		auto ownFields = _fields.sliceFrom(baseFieldCount);

		ownFields[0] = &field_center;
		ownFields[1] = &field_size;

		type->_fields    = _fields.span();
		type->_ownFields = ownFields;
	}

};

void GEO_Cube::s_initRtti(axType* type) {
	static Spec spec(type);
}

const GEO_Cube::Spec* GEO_Cube::Spec::s_instance = nullptr;

void GEO_Cube::onInitProps() {
	Base::onInitProps();
	auto* spec = Spec::s_instance;
	_initProp(spec->field_center, center);
	_initProp(spec->field_size, size);
}

bool GEO_Cube::onReadJsonProp(axJsonReader& rd_) {
	bool _ret = Base::onReadJsonProp(rd_);
	if (rd_.isMember("center")) { rd_.readValue(center); _ret = true; }
	if (rd_.isMember("size")) { rd_.readValue(size); _ret = true; }
	return _ret;
}

void GEO_Cube::onWriteJsonProp(axJsonWriter& wr_) const {
	Base::onWriteJsonProp(wr_);
	wr_.writeMember("center", center);
	wr_.writeMember("size", size);
}

} // namespace 
