//==============================================================//
//                                                              //
//       This file is generated by axNodeGen                    //
//                                                              //
//==============================================================//

#include "GEO_WaveFrontObj.h"

namespace Anon{ 

struct GEO_WaveFrontObj::Spec : public AnonObjectSpec {
	struct Field_filename : public axFieldInfo {
		Field_filename(axType* type) : axFieldInfo(type, &GEO_WaveFrontObj::_filename, "filename", "Filename") {
		}
		virtual void onSetToDefaultValue(axValuePtr& data) const final {
			data.value<String>() = String();
		};
	};
	Field_filename field_filename;

	static const Spec* s_instance;

	axArray<axFieldInfo*, 16> _fields;

	Spec(axType* type)
		: AnonObjectSpec(type)
		, field_filename(type)
	{
		s_instance = this;
		axInt ownFieldCount = 1;
		auto baseFieldCount = type->_baseClass->fields().size();
		_fields.resize(ownFieldCount + baseFieldCount);
		_fields.slice(0, baseFieldCount).copyValues(type->_baseClass->fields());
		auto ownFields = _fields.sliceFrom(baseFieldCount);

		ownFields[0] = &field_filename;

		type->_fields    = _fields.span();
		type->_ownFields = ownFields;
	}

};

void GEO_WaveFrontObj::s_initRtti(axType* type) {
	static Spec spec(type);
}

const GEO_WaveFrontObj::Spec* GEO_WaveFrontObj::Spec::s_instance = nullptr;

void GEO_WaveFrontObj::onInitProps() {
	Base::onInitProps();
	auto* spec = Spec::s_instance;
	_initProp(spec->field_filename, _filename);
}

bool GEO_WaveFrontObj::onReadJsonProp(axJsonReader& rd_) {
	bool _ret = Base::onReadJsonProp(rd_);
	if (rd_.isMember("filename")) { rd_.readValue(_filename); _ret = true; }
	return _ret;
}

void GEO_WaveFrontObj::onWriteJsonProp(axJsonWriter& wr_) const {
	Base::onWriteJsonProp(wr_);
	wr_.writeMember("filename", _filename);
}

} // namespace 
