/* !!! Generated by libax_common.cmake */ 
#pragma once

#include "axColor.h"
#include "axColorA.h"
#include "axColorBGRA.h"
#include "axColorCompressed.h"
#include "axColorElement.h"
#include "axColorHSBA.h"
#include "axColorL.h"
#include "axColorLA.h"
#include "axColorR.h"
#include "axColorR5G5B5A1.h"
#include "axColorR5G6B5.h"
#include "axColorRG.h"
#include "axColorRGB.h"
#include "axColorRGBA.h"
#include "axColorUtil.h"
