/* !!! Generated by libax_common.cmake */ 
#pragma once

#include "ax_ui_config.h"
#include "base/_ALL_base.h"
#include "diagram/_ALL_diagram.h"
#include "dock/_ALL_dock.h"
#include "input/_ALL_input.h"
#include "layout/_ALL_layout.h"
#include "menu/_ALL_menu.h"
#include "text/_ALL_text.h"
#include "widget/_ALL_widget.h"
