//==============================================================//
//                                                              //
//       This file is generated by axNodeGen                    //
//                                                              //
//==============================================================//

#include "GEO_CopyToPoints.h"

namespace Anon{ 

struct GEO_CopyToPoints::Spec : public AnonObjectSpec {
	struct Field_inputPoints : public axFieldInfo {
		Field_inputPoints(axType* type) : axFieldInfo(type, &GEO_CopyToPoints::_inputPoints, "inputPoints", "Input Points") {
		}
		virtual void onSetToDefaultValue(axValuePtr& data) const final {
			data.value<GEO_GeoData>() = GEO_GeoData();
		};
	};
	Field_inputPoints field_inputPoints;

	static const Spec* s_instance;

	axArray<axFieldInfo*, 16> _fields;

	Spec(axType* type)
		: AnonObjectSpec(type)
		, field_inputPoints(type)
	{
		s_instance = this;
		axInt ownFieldCount = 1;
		auto baseFieldCount = type->_baseClass->fields().size();
		_fields.resize(ownFieldCount + baseFieldCount);
		_fields.slice(0, baseFieldCount).copyValues(type->_baseClass->fields());
		auto ownFields = _fields.sliceFrom(baseFieldCount);

		ownFields[0] = &field_inputPoints;

		type->_fields    = _fields.span();
		type->_ownFields = ownFields;
	}

};

void GEO_CopyToPoints::s_initRtti(axType* type) {
	static Spec spec(type);
}

const GEO_CopyToPoints::Spec* GEO_CopyToPoints::Spec::s_instance = nullptr;

void GEO_CopyToPoints::onInitProps() {
	Base::onInitProps();
	auto* spec = Spec::s_instance;
	_initProp(spec->field_inputPoints, _inputPoints);
}

bool GEO_CopyToPoints::onReadJsonProp(axJsonReader& rd_) {
	bool _ret = Base::onReadJsonProp(rd_);
	if (rd_.isMember("inputPoints")) { rd_.readValue(_inputPoints); _ret = true; }
	return _ret;
}

void GEO_CopyToPoints::onWriteJsonProp(axJsonWriter& wr_) const {
	Base::onWriteJsonProp(wr_);
	wr_.writeMember("inputPoints", _inputPoints);
}

} // namespace 
