//==============================================================//
//                                                              //
//       This file is generated by axNodeGen                    //
//                                                              //
//==============================================================//

#include "GEO_Merge.h"

namespace Anon{ 

struct GEO_Merge::Spec : public AnonObjectSpec {
	struct Field_input2 : public axFieldInfo {
		Field_input2(axType* type) : axFieldInfo(type, &GEO_Merge::_input2, "input2", "Input2") {
			static DontSaveAttribute DontSave;
			static axAttribute* attrs[] = {&DontSave};
			_attributes = axSpan_make(attrs);
		}
		virtual void onSetToDefaultValue(axValuePtr& data) const final {
			data.value<GEO_GeoData>() = GEO_GeoData();
		};
	};
	Field_input2 field_input2;

	static const Spec* s_instance;

	axArray<axFieldInfo*, 16> _fields;

	Spec(axType* type)
		: AnonObjectSpec(type)
		, field_input2(type)
	{
		s_instance = this;
		axInt ownFieldCount = 1;
		auto baseFieldCount = type->_baseClass->fields().size();
		_fields.resize(ownFieldCount + baseFieldCount);
		_fields.slice(0, baseFieldCount).copyValues(type->_baseClass->fields());
		auto ownFields = _fields.sliceFrom(baseFieldCount);

		ownFields[0] = &field_input2;

		type->_fields    = _fields.span();
		type->_ownFields = ownFields;
	}

};

void GEO_Merge::s_initRtti(axType* type) {
	static Spec spec(type);
}

const GEO_Merge::Spec* GEO_Merge::Spec::s_instance = nullptr;

void GEO_Merge::onInitProps() {
	Base::onInitProps();
	auto* spec = Spec::s_instance;
	_initProp(spec->field_input2, _input2);
}

bool GEO_Merge::onReadJsonProp(axJsonReader& rd_) {
	bool _ret = Base::onReadJsonProp(rd_);
	return _ret;
}

void GEO_Merge::onWriteJsonProp(axJsonWriter& wr_) const {
	Base::onWriteJsonProp(wr_);
}

} // namespace 
