/* !!! Generated by libax_common.cmake */ 
#pragma once

#include "AssetsPanel/_ALL_AssetsPanel.h"
#include "ConsolePanel/_ALL_ConsolePanel.h"
#include "DiagramPanel/_ALL_DiagramPanel.h"
#include "EditorPanel.h"
#include "InspectorPanel/_ALL_InspectorPanel.h"
#include "SceneOutlinerPanel/_ALL_SceneOutlinerPanel.h"
#include "SceneViewPanel/_ALL_SceneViewPanel.h"
