//==============================================================//
//                                                              //
//       This file is generated by axNodeGen                    //
//                                                              //
//==============================================================//

#include "GEO_Modifier.h"

namespace Anon{ 

struct GEO_Modifier::Spec : public AnonObjectSpec {
	struct Field_input : public axFieldInfo {
		Field_input(axType* type) : axFieldInfo(type, &GEO_Modifier::_input, "input", "Input") {
			static DontSaveAttribute DontSave;
			static axAttribute* attrs[] = {&DontSave};
			_attributes = axSpan_make(attrs);
		}
		virtual void onSetToDefaultValue(axValuePtr& data) const final {
			data.value<GEO_GeoData>() = GEO_GeoData();
		};
	};
	Field_input field_input;

	static const Spec* s_instance;

	axArray<axFieldInfo*, 16> _fields;

	Spec(axType* type)
		: AnonObjectSpec(type)
		, field_input(type)
	{
		s_instance = this;
		axInt ownFieldCount = 1;
		auto baseFieldCount = type->_baseClass->fields().size();
		_fields.resize(ownFieldCount + baseFieldCount);
		_fields.slice(0, baseFieldCount).copyValues(type->_baseClass->fields());
		auto ownFields = _fields.sliceFrom(baseFieldCount);

		ownFields[0] = &field_input;

		type->_fields    = _fields.span();
		type->_ownFields = ownFields;
	}

};

void GEO_Modifier::s_initRtti(axType* type) {
	static Spec spec(type);
}

const GEO_Modifier::Spec* GEO_Modifier::Spec::s_instance = nullptr;

void GEO_Modifier::onInitProps() {
	Base::onInitProps();
	auto* spec = Spec::s_instance;
	_initProp(spec->field_input, _input);
}

bool GEO_Modifier::onReadJsonProp(axJsonReader& rd_) {
	bool _ret = Base::onReadJsonProp(rd_);
	return _ret;
}

void GEO_Modifier::onWriteJsonProp(axJsonWriter& wr_) const {
	Base::onWriteJsonProp(wr_);
}

} // namespace 
