//==============================================================//
//                                                              //
//       This file is generated by axNodeGen                    //
//                                                              //
//==============================================================//

#include "GEO_Subdiv.h"

namespace Anon{ 

struct GEO_Subdiv::Spec : public AnonObjectSpec {
	struct Field_level : public axFieldInfo {
		Field_level(axType* type) : axFieldInfo(type, &GEO_Subdiv::_level, "level", "Level") {
			static SliderAttribute Slider(1,5);
			static axAttribute* attrs[] = {&Slider};
			_attributes = axSpan_make(attrs);
		}
		virtual void onSetToDefaultValue(axValuePtr& data) const final {
			data.value<axInt>() = 1;
		};
	};
	Field_level field_level;

	static const Spec* s_instance;

	axArray<axFieldInfo*, 16> _fields;

	Spec(axType* type)
		: AnonObjectSpec(type)
		, field_level(type)
	{
		s_instance = this;
		axInt ownFieldCount = 1;
		auto baseFieldCount = type->_baseClass->fields().size();
		_fields.resize(ownFieldCount + baseFieldCount);
		_fields.slice(0, baseFieldCount).copyValues(type->_baseClass->fields());
		auto ownFields = _fields.sliceFrom(baseFieldCount);

		ownFields[0] = &field_level;

		type->_fields    = _fields.span();
		type->_ownFields = ownFields;
	}

};

void GEO_Subdiv::s_initRtti(axType* type) {
	static Spec spec(type);
}

const GEO_Subdiv::Spec* GEO_Subdiv::Spec::s_instance = nullptr;

void GEO_Subdiv::onInitProps() {
	Base::onInitProps();
	auto* spec = Spec::s_instance;
	_initProp(spec->field_level, _level);
}

bool GEO_Subdiv::onReadJsonProp(axJsonReader& rd_) {
	bool _ret = Base::onReadJsonProp(rd_);
	if (rd_.isMember("level")) { rd_.readValue(_level); _ret = true; }
	return _ret;
}

void GEO_Subdiv::onWriteJsonProp(axJsonWriter& wr_) const {
	Base::onWriteJsonProp(wr_);
	wr_.writeMember("level", _level);
}

} // namespace 
