/* !!! Generated by libax_common.cmake */ 
#pragma once

#include "axRenderIndexArray.h"
#include "axRenderVertex.h"
#include "axRenderVertexArray.h"
#include "axRenderVertexBase_Generated.h"
#include "axRenderVertexDesc.h"
#include "axRenderVertexType.h"
#include "axRenderVertex_Generated.h"
