/* !!! Generated by libax_common.cmake */ 
#pragma once

#include "axMaterial.h"
#include "axMaterialPass.h"
#include "axRenderState.h"
#include "axRenderUniformBuffer.h"
#include "axShader.h"
#include "axShaderInfo.h"
#include "axShaderPass.h"
