/* !!! Generated by libax_common.cmake */ 
#pragma once

#include "dx11/_ALL_dx11.h"
#include "dx12/_ALL_dx12.h"
#include "metal/_ALL_metal.h"
#include "opengl/_ALL_opengl.h"
#include "vulkan/_ALL_vulkan.h"
